### ISSUE TITLE
Uncaught Exception:  Error: ENOENT: no such file or directory .local/share/code-server/Backups/workspaces.json

### ISSUE THREAD

**Issue by andrewssobral** [betatim/vscode-binder#2]
Hi @betatim ,
First I'd like to thank you for this great plugin.
However, some times I got the following error in my jupyter lab terminal:
```
INFO  code-server v1.32.0-282
INFO  Additional documentation: http://github.com/codercom/code-server
INFO  Initializing {"data-dir":"/Users/andrewssobral/.local/share/code-server","working-dir":"/Users/andrewssobral/Projects","log-dir":"/Users/andrewssobral/.cache/code-server/logs/20190317003928880"}
INFO  Starting webserver... {"host":"0.0.0.0","port":60464}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://coder.com/docs
WARN  Launched without authentication.
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:60464/
INFO   
INFO  Starting shared process [1/5]...
[I 01:39:30.926 LabApp] Trying to establish websocket connection to ws://localhost:60464/
[I 01:39:30.937 LabApp] Websocket connection established to ws://localhost:60464/
INFO  WebSocket opened / {"client":1,"ip":"127.0.0.1"}
INFO  Connected to shared process
ERROR SHARED stderr {"data":"Uncaught Exception:  Error: Unexpected end of JSON input\n\nSyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at pfs_1.readFile.then.contents (eval at exports.requireModule (/usr/local/bin/code-server:468:27661), <anonymous>:77406:45)\n    at <anonymous>\n    at Timeout.setTimeout [as _onTimeout] (eval at exports.requireModule (/usr/local/bin/code-server:468:27661), <anonymous>:52669:31)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)\n"}
```
and it freezes the jupyter lab web interface as well the code-server web interface.
I tried to do this manually:
```
mkdir  /Users/andrewssobral/.local/share/code-server/Backups/
touch /Users/andrewssobral/.local/share/code-server/Backups/workspaces.json
```
but the error persist. Do you know what it can be?

**Comment by andrewssobral** [comment]
Sorry, I found this issue on code-server project https://github.com/codercom/code-server/issues/121
