### ISSUE TITLE
Make this repo work with python and jupyter extensions

### ISSUE THREAD

**Issue by MarcSkovMadsen** [betatim/vscode-binder#30]
Making the Python and Jupyter extensions work nicely on code-server is not easy. You can see that from other issues in this repo and from the code-server github issues list. You need specific versions of code-server and specific versions of the python and jupyter extensions.

My suggestion would be to pin versions of code-server, python extension and jupyter extension to something that works.

Would be really helpful.

(Unfortunately I don't know recent version that work well together. I'm trying to find them.)

**Comment by betatim** [comment]
That would be a great contribution. I made this repo as an example but I don't really use VS Code (or any of its extensions) so my experience on how to make things work is limited :-/ If you figure something out and can open a PR that would be great.

**Comment by benz0li** [comment]
@MarcSkovMadsen The Python and Jupyter extension work fine with code-server. But yes, up to v3.12.0 it was difficult to find a _compatible set_.

You may give my _reference deployment_ at https://demo.jupyter.b-data.ch another try which serves JupyterHub and JupyterLab + code-server.

Most issues are related to either https://github.com/coder/code-server/issues/4395#issuecomment-1023506885 or https://github.com/coder/code-server/issues/4689#issuecomment-1006410126, i.e. trying to run it locally without HTTPS.

---

**Run it locally with docker**

Initial command:

```bash
docker run -it --rm -p 8888:8888 -v $PWD:/home/jovyan -e GEN_CERT=yes registry.gitlab.b-data.ch/jupyterlab/r/verse
```

Subsequent command:

```bah
docker run -it --rm -p 8888:8888 -v $PWD:/home/jovyan registry.gitlab.b-data.ch/jupyterlab/r/verse start-notebook.sh --NotebookApp.certfile=~/.local/share/jupyter/notebook.pem
```

Run the initial command in an empty directory so that the container populates it. Visit `https://127.0.0.1:8888/lab?token=<token>` in a browser to load JupyterLab.

**Comment by enryH** [comment]
I forked the [repository](https://github.com/cphbiosciencephd/vscode-binder) and tried to start it using [mybinder (direk-link)](https://mybinder.org/v2/gh/cphbiosciencephd/vscode-binder/HEAD).

and now I see errors:

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/jedi_language_server/cli.py", line 7, in <module>
    from .server import SERVER
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/jedi_language_server/server.py", line 14, in <module>
    from pydantic import ValidationError
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/pydantic/dataclasses.py", line 3, in <module>
    from .class_validators import gather_all_validators
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/pydantic/class_validators.py", line 8, in <module>
    from .errors import ConfigError
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/pydantic/errors.py", line 5, in <module>
    from .typing import display_as_type
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/pydantic/typing.py", line 23, in <module>
    from typing_extensions import Annotated, Literal
  File "/srv/conda/envs/notebook/share/code-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/jedilsp/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
[Error - 3:04:49 PM] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 3:04:49 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

I don't get the error when I use the original link. might the images be build differently lately?

**Comment by enryH** [comment]
The most striking differencens: 
- code-server (betatim docker container): 4.1 to 4.5 on fork with rebuild container
- jupyter-server also changed
- jupyter-server-proxy stayed the same
![image](https://user-images.githubusercontent.com/2833836/178112013-b35b74cc-945d-492f-a323-1126d665e6e4.png)
![image](https://user-images.githubusercontent.com/2833836/178112346-8eb63a6b-a82a-478e-a52e-6b643c031313.png)

**Comment by enryH** [comment]
It works if I set code-server to version `4.1.0` (different project): 
https://github.com/enryH/snakemake-tutorial/commit/85d02801563c15d14ad92a5cb03686091b41c085
