### ISSUE TITLE
Proxy breaks with VSCode >= v4.10.1

### ISSUE THREAD

**Issue by TobiasGoerke** [betatim/vscode-binder#38]
Hey and thank you for creating and maintaining this very useful plugin!

We've been using it for quite a while but noticed it doesn't work for newer VSCode versions.

Reading the proxy's log, it becomes evident it cannot open up a WebSocket connection. [I assume this is due to VSCode requiring an origin header starting with VSCode 4.10.1.](https://github.com/coder/code-server/releases/tag/v4.10.1)
You can even see it failing at "ensureOrigin".

As a temporary fix: using v4.10.0 works fine.

Thanks!

```
[10:52:31] Extension host agent started. 
74 [I 2023-04-03 10:52:31.943 ServerApp] 302 GET /notebook/maintenance/vscodetest1/vscode/ (
[a9e108fcab8048ec8cc42b232683806b@127.0.0.6](mailto:a9e108fcab8048ec8cc42b232683806b@127.0.0.6)
) 1669.19ms 
75 [I 2023-04-03 10:52:33.471 ServerApp] Trying to establish websocket connection to ws://localhost:44579/stable-5e805b79fcb6ba4c2d23712967df89a089da575b?reconnectionToken=b74173bd-079c-415c-a1dc-61e514670497&reconnection=false&skipWebSocketFrames=false 
76 [2023-04-03T08:52:33.476Z] error Forbidden HttpError: Forbidden 
77     at ensureOrigin (/usr/lib/code-server/out/node/http.js:288:15) 
78     at wrapped (/usr/lib/code-server/out/node/wsRouter.js:64:24) 
79     at Layer.handle [as handle_request] (/usr/lib/code-server/node_modules/router/lib/layer.js:102:15) 
80     at next (/usr/lib/code-server/node_modules/router/lib/route.js:144:13) 
81     at Route.dispatch (/usr/lib/code-server/node_modules/router/lib/route.js:109:3) 
82     at handle (/usr/lib/code-server/node_modules/router/index.js:515:11) 
83     at Layer.handle [as handle_request] (/usr/lib/code-server/node_modules/router/lib/layer.js:102:15) 
84     at /usr/lib/code-server/node_modules/router/index.js:291:22 
85     at param (/usr/lib/code-server/node_modules/router/index.js:368:14) 
86     at param (/usr/lib/code-server/node_modules/router/index.js:379:14) 
87     at Function.process_params (/usr/lib/code-server/node_modules/router/index.js:424:3) 
88     at next (/usr/lib/code-server/node_modules/router/index.js:285:10) 
89     at Function.handle (/usr/lib/code-server/node_modules/router/index.js:184:3) 
90     at router (/usr/lib/code-server/node_modules/router/index.js:59:12) 
91     at Layer.handle [as handle_request] (/usr/lib/code-server/node_modules/router/lib/layer.js:102:15) 
92     at trim_prefix (/usr/lib/code-server/node_modules/router/index.js:330:13) 
93     at /usr/lib/code-server/node_modules/router/index.js:294:7 
94     at Function.process_params (/usr/lib/code-server/node_modules/router/index.js:349:12) 
95     at Immediate.next (/usr/lib/code-server/node_modules/router/index.js:285:10) 
96     at Immediate.<anonymous> (/usr/lib/code-server/node_modules/router/index.js:671:15) 
97     at processImmediate (node:internal/timers:468:21) 
98 [E 2023-04-03 10:52:33.477 ServerApp] Uncaught exception GET /notebook/maintenance/vscodetest1/vscode/stable-5e805b79fcb6ba4c2d23712967df89a089da575b?reconnectionToken=b74173bd-079c-415c-a1dc-61e514670497&reconnection=false&skipWebSocketFrames=false (127.0.0.6)
```

**Comment by ehfd** [comment]
@xhochy @krassowski Has this been fixed or not? Can it be fixed?

**Comment by krassowski** [comment]
I am running latest version of code-server without any issues. This issue is unclear to me as it mentions VSCode brand name but does not specify if it relates to usage of code server or openvscode server or an attempt to run vanilla VSCode which I don't know if ever worked well.
